### ISSUE TITLE
Password reset gave me "Unexpected Error"

### ISSUE THREAD

**Issue by ktbyers** [jasoncrawford/freeobjectivistbooks#14]
I wanted to reset my password to make a new donation.

URL https://secure.freeobjectivistbooks.org/password/request_reset
Email address 'ktbyersx@gmail.com'

**Comment by jasoncrawford** [comment]
Hi Kirk. Where did you get that link from? This is the reset link:

https://secure.freeobjectivistbooks.org/password/forgot

**Comment by jasoncrawford** [comment]
Oh, I see. If you enter your email on the “forgot” page it gets an error. I'll investigate

**Comment by jasoncrawford** [comment]
@ktbyers There was a problem with our outbound mail config in production. This is fixed now and you should have gotten your password reset link. Thanks for the report!
